/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./views/**', './src/**/*.js', './public/**/*'],
  theme: {
    extend: {
      colors: {
        primary: '#785a00',
        'primary-container': '#f4bd31',
        'primary-fixed': '#ffdf9d',
        'primary-fixed-dim': '#f5be32',
        'on-primary': '#ffffff',
        'on-primary-container': '#694d00',
        'on-primary-fixed': '#251a00',
        'on-primary-fixed-variant': '#5b4300',
        'inverse-primary': '#f5be32',
        secondary: '#5e5e5e',
        'secondary-container': '#e2e2e2',
        'secondary-fixed': '#e2e2e2',
        'secondary-fixed-dim': '#c6c6c6',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#646464',
        'on-secondary-fixed': '#1b1b1b',
        'on-secondary-fixed-variant': '#474747',
        tertiary: '#5d5f5f',
        'tertiary-container': '#c4c5c5',
        'tertiary-fixed': '#e2e2e2',
        'tertiary-fixed-dim': '#c6c6c7',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#505252',
        'on-tertiary-fixed': '#1a1c1c',
        'on-tertiary-fixed-variant': '#454747',
        surface: '#f9f9f9',
        'surface-dim': '#dadada',
        'surface-bright': '#f9f9f9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f3f3',
        'surface-container': '#eeeeee',
        'surface-container-high': '#e8e8e8',
        'surface-container-highest': '#e2e2e2',
        'surface-variant': '#e2e2e2',
        'surface-tint': '#785a00',
        'on-surface': '#1a1c1c',
        'on-surface-variant': '#4f4634',
        'inverse-surface': '#2f3131',
        'inverse-on-surface': '#f1f1f1',
        outline: '#817661',
        'outline-variant': '#d3c5ad',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        background: '#f9f9f9',
        'on-background': '#1a1c1c',
        whatsapp: {
          DEFAULT: '#25D366',
          dark: '#128C7E',
          light: '#DCF8C6',
          hover: '#1DA851',
        },
      },
      fontFamily: {
        'headline-lg': ['Pixelify Sans', 'sans-serif'],
        'headline-md': ['Pixelify Sans', 'sans-serif'],
        'headline-lg-mobile': ['Pixelify Sans', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-md': ['Space Mono', 'monospace'],
        'label-sm': ['Space Mono', 'monospace'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['40px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.0', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '1.0', fontWeight: '500' }],
      },
      spacing: {
        'margin-mobile': '16px',
        'margin-desktop': '32px',
        gutter: '16px',
        unit: '4px',
      },
      borderWidth: {
        'border-width-thin': '1px',
        'border-width-thick': '3px',
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
