import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#785a00",
        "primary-container": "#f4bd31",
        "primary-fixed": "#ffdf9d",
        "primary-fixed-dim": "#f5be32",
        "on-primary": "#ffffff",
        "on-primary-container": "#694d00",
        "on-primary-fixed": "#251a00",
        "on-primary-fixed-variant": "#5b4300",
        "inverse-primary": "#f5be32",
        secondary: "#5e5e5e",
        "secondary-container": "#e2e2e2",
        "secondary-fixed": "#e2e2e2",
        "secondary-fixed-dim": "#c6c6c6",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#646464",
        "on-secondary-fixed": "#1b1b1b",
        "on-secondary-fixed-variant": "#474747",
        tertiary: "#5d5f5f",
        "tertiary-container": "#c4c5c5",
        "tertiary-fixed": "#e2e2e2",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#505252",
        "on-tertiary-fixed": "#1a1c1c",
        "on-tertiary-fixed-variant": "#454747",
        surface: "#f9f9f9",
        "surface-dim": "#dadada",
        "surface-bright": "#f9f9f9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f3f3",
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "surface-variant": "#e2e2e2",
        "surface-tint": "#785a00",
        "on-surface": "#1a1c1c",
        "on-surface-variant": "#4f4634",
        "inverse-surface": "#2f3131",
        "inverse-on-surface": "#f1f1f1",
        outline: "#817661",
        "outline-variant": "#d3c5ad",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        background: "#f9f9f9",
        "on-background": "#1a1c1c",
        whatsapp: "#25D366",
        whatsappDark: "#128C7E",
        whatsappLight: "#DCF8C6",
        whatsappHover: "#1DA851",
      },
      fontFamily: {
        headline: ['"Pixelify Sans"', "sans-serif"],
        body: ['"Inter"', "sans-serif"],
        mono: ['"Space Mono"', "monospace"],
      },
      fontSize: {
        "headline-lg": ["40px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl": ["56px", { lineHeight: "1.05", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-xl-mobile": ["40px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.0", letterSpacing: "0", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "1.0", letterSpacing: "0", fontWeight: "500" }],
      },
      spacing: {
        gutter: "16px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
      },
      boxShadow: {
        brutalist: "4px 4px 0px #1a1c1c",
        "brutalist-sm": "2px 2px 0px #1a1c1c",
        "brutalist-lg": "8px 8px 0px #1a1c1c",
        glow: "0 0 15px rgba(244, 189, 49, 0.4)",
        "glow-lg": "0 0 30px rgba(244, 189, 49, 0.5)",
      },
      borderWidth: {
        thin: "1px",
        DEFAULT: "3px",
        thick: "4px",
      },
      borderRadius: {
        none: "0px",
        DEFAULT: "0px",
        md: "0px",
        lg: "0px",
        xl: "0px",
        "2xl": "0px",
        full: "0px",
      },
      animation: {
        "float": "float 6s ease-in-out infinite",
        "float-delayed": "float 6s ease-in-out 2s infinite",
        "float-slow": "float 8s ease-in-out 1s infinite",
        "pulse-slow": "pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "grid-move": "gridMove 20s linear infinite",
        "glow": "glow 2s ease-in-out infinite alternate",
        "slide-up": "slideUp 0.6s ease-out forwards",
        "slide-down": "slideDown 0.4s ease-out forwards",
        "fade-in": "fadeIn 0.5s ease-out forwards",
        "scale-in": "scaleIn 0.4s ease-out forwards",
        "marquee": "marquee 30s linear infinite",
        "spin-slow": "spin 8s linear infinite",
        "bounce-slow": "bounce 3s infinite",
        "draw": "draw 2s ease-out forwards",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0px) rotate(0deg)" },
          "50%": { transform: "translateY(-20px) rotate(3deg)" },
        },
        gridMove: {
          "0%": { transform: "translate(0, 0)" },
          "100%": { transform: "translate(20px, 20px)" },
        },
        glow: {
          "0%": { boxShadow: "0 0 5px #f4bd31, 0 0 10px #f4bd31" },
          "100%": { boxShadow: "0 0 20px #f4bd31, 0 0 30px #f4bd31" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(40px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        slideDown: {
          "0%": { opacity: "0", transform: "translateY(-20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        scaleIn: {
          "0%": { opacity: "0", transform: "scale(0.9)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        marquee: {
          "0%": { transform: "translateX(0%)" },
          "100%": { transform: "translateX(-50%)" },
        },
        draw: {
          "0%": { strokeDashoffset: "1000" },
          "100%": { strokeDashoffset: "0" },
        },
      },
    },
  },
  plugins: [],
} satisfies Config;
