import { config } from '../config.js';
import { generateJSON } from './openai.js';
import { DAILY_REPORT_SYSTEM_PROMPT, DAILY_REPORT_USER_PROMPT } from '../prompts/daily-report.js';
import { getAnalyticsData } from './data-fetcher.js';
import type { AIReport } from '../types/index.js';

export async function generateDailyReport(date?: string): Promise<AIReport> {
  const targetDate = date || getTodayDate();
  console.log(`[Summarizer] Generating daily report for ${targetDate}...`);

  try {
    const analyticsData = await getAnalyticsData(targetDate);

    const userPrompt = DAILY_REPORT_USER_PROMPT(JSON.stringify(analyticsData, null, 2));
    const result = await generateJSON<any>(DAILY_REPORT_SYSTEM_PROMPT, userPrompt);

    const markdown = generateMarkdown(targetDate, result);

    const report: AIReport = {
      date: targetDate,
      type: 'daily',
      title: `Daily Report — ${targetDate}`,
      summary: result.summary || 'No summary generated',
      kpis: result.kpis || [],
      insights: result.insights || [],
      recommendations: result.recommendations || [],
      anomalies: result.anomalies || [],
      rawMarkdown: markdown,
      generatedAt: new Date().toISOString(),
    };

    console.log(`[Summarizer] Report generated with ${report.kpis.length} KPIs, ${report.insights.length} insights`);
    return report;
  } catch (error) {
    console.error('[Summarizer] Error:', error);
    return {
      date: targetDate,
      type: 'daily',
      title: `Daily Report — ${targetDate}`,
      summary: 'Failed to generate AI report',
      kpis: [],
      insights: [{ category: 'Error', title: 'Report generation failed', description: String(error), severity: 'critical' }],
      recommendations: [],
      anomalies: [],
      rawMarkdown: `# Daily Report — ${targetDate}\n\nFailed to generate AI report: ${error}`,
      generatedAt: new Date().toISOString(),
    };
  }
}

function generateMarkdown(date: string, data: any): string {
  const kpiRows = (data.kpis || []).map((k: any) => {
    const emoji = k.trend === 'up' ? '📈' : k.trend === 'down' ? '📉' : '➡️';
    return `| ${k.metric} | ${k.value} | ${k.change > 0 ? '+' : ''}${k.change}% | ${emoji} | ${k.status} |`;
  }).join('\n');

  const insightItems = (data.insights || []).map((i: any) => {
    const emoji = i.severity === 'critical' ? '🚨' : i.severity === 'warning' ? '⚠️' : '💡';
    return `### ${emoji} ${i.title}\n${i.description}\n`;
  }).join('\n');

  const recoItems = (data.recommendations || []).map((r: any) => {
    const pri = r.priority === 'high' ? '🔴' : r.priority === 'medium' ? '🟡' : '🟢';
    return `- ${pri} **[${r.area}]** ${r.action}\n  - *Expected Impact:* ${r.expectedImpact}`;
  }).join('\n');

  const anomalyItems = (data.anomalies || []).map((a: any) => {
    return `- 🚩 **${a.metric}:** Expected ${a.expectedValue}, got ${a.actualValue} (${a.deviation > 0 ? '+' : ''}${a.deviation}%) — ${a.description}`;
  }).join('\n');

  return `# Daily Report — ${date}

> ${data.summary || 'AI-powered summary of today\'s analytics.'}

## Key Metrics

| Metric | Value | Change | Trend | Status |
|--------|-------|--------|-------|--------|
${kpiRows || '| No data | — | — | — | — |'}

## Insights

${insightItems || 'No insights generated.'}

## Recommendations

${recoItems || 'No recommendations generated.'}

## Anomalies

${anomalyItems || 'No anomalies detected.'}

---
*Generated by SplitSquad AI Analytics Engine at ${new Date().toISOString()}*
`;
}

function getTodayDate(): string {
  return new Date().toISOString().split('T')[0];
}
